version: '3.1'

services:
  db:
    image: mysql:8.3.0
    container_name: go-money-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: go_money
    ports:
      - 3346:3306

  adminer:
    image: adminer
    container_name: go-money-adminer
    restart: always
    ports:
      - 8081:8080